# bank-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybank-deployment
  labels:
    app: bank-app
spec:
  # Run 2 copies (replicas) of your application
  replicas: 2 
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
      - name: bank-container
        # Use the image you just built
        image: mybank-app:v1 
        # Crucial for Minikube: tells K8s not to pull the image from Docker Hub
        imagePullPolicy: Never 
        # If your app had a web interface, you'd specify a port here
        # ports:
        # - containerPort: 8080